### ISSUE TITLE
ToDo list tutorial update for mlr 2.10

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#47]
This is important:
- [x] new confusion/ROC matrix
  pages: predict, roc_analysis
  This is probably very outdated, maybe create an extra page
  Merge Janek's PR #48 
- [x] merge Mason's PR #43

finish create_learner page
- [ ] issue #26
- [x] issue #39
- [ ] issue #54
- [x] issue #67 
- [x] explain how to create a new getFeatureImportance method (fixes issue #51)

- [x] inside-r.org is decommissioned, therefore some links don't work anymore.

These are just some things to check or mini adjustments:
- [x] in benchmark learners can be specified by character strings
- [ ] mention `makeLearners`
- [ ] `getLearnerId`, `getLearnerType`, `getLearnerPredictType`, `getLearnerPackages`, `getLearnerParamSet`, `getLearnerParVals`, `getLearnerShortName`
  page: Learner
- [ ] We have now learner property featimp. This must be integrated better in the learner tables.
  Theoretically, we need a new column for this, but the tables are already too wide.
  Same for oobpreds.
  See also #60.
- [x] Renamed rf.importance filter (now deprecated) to randomForestSRC.var.rfsrc
    Renamed rf.min.depth filter (now deprecated) to randomForestSRC.var.select
  pages: featsel (check if this causes any problems)
  No problems
- [x] makeLearner, setHyperPars: if you mistype a hyperpar name, mlr uses
  fuzzy matching to suggest the 3 closest names in the message
  pages: configureMlr, learner
- [ ] tuning: tuning with irace is now also parallelized, i.e., different
  learner config are evaluated in parallel.
- [x] subsetTask, getTaskData: arg "features" now also accepts logical and integer
  pages: Task (just check)
  No problems
- [ ] makeRemoveConstantFeaturesWrapper can be used to augment a learner with this
  preprocessing step.
  pages: preproc
- [x] getNestedTuneResultsOptPathDf: added new arg "trafo"
  pages: nested resampling (just see if it still checks out)
  No problems
- [x] improve documentation for permutation.importance filter and perform slight
  argument renaming to fix potential name clashes
  pages: feature selection (check if anything breaks)
  No problems
- [x] generateFilterValuesData: added argument 'more.args'
  pages: feature selection (check if anything breaks)
  No problems
- [ ] makeConstantClassWrapper
  this is new, should it be mentioned somewhere?
- [x] getParamSet generic was removed (now in ParamHelpers package)
  does this break any documentation links?
  No, there is still a doc page with this name
- [x] multiclass.auc was renamed to multiclass.au1u
  pages: roc_analysis (add info about the several new mutliclass.auc variants)
- [x] Fixed a bug where the resampling objects hout, cv2, cv3, cv5, cv10 were not documented
  in the ResampleDesc help page
  pages: resample (I think these objects are not mentioned there)
- [x] getRRPredictionList, addRRMeasure, getRRTaskDescription, getRRPredictions
- [ ] plotResiduals
- [ ] getFeatureImportanceLearner, getFeatureImportance + potential changes/improvements in filters
- [ ] New "dummy" learners (that disregard features completely) can be fitted now for baseline
comparisons, see "featureless" learners below.
- [ ] createDummyFeatures
