### ISSUE TITLE
ToDo list tutorial updates for mlr 2.11

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr-tutorial#76]
Very Important: Complete create_learner page
- [ ] issue #26
- [ ] issue #54

Also very important: Improve the quick start page / write use cases
- [ ] issue #56 
- [ ] write a use case for clustering #71 

These are just some things to check or mini adjustments:
- [x] maybe mention `makeLearners`
- [x] `getLearnerId`, `getLearnerType`, `getLearnerPredictType`, `getLearnerPackages`, `getLearnerParamSet`, `getLearnerParVals`, `getLearnerShortName`
  page: Learner
- [x] We have now learner properties feat imp and oobpreds. These should be integrated better in the learner tables.
  Theoretically, we need new columns, but the tables are already too wide.
  See also #60.
- [x] makeRemoveConstantFeaturesWrapper can be used to augment a learner with this
  preprocessing step.
  pages: preproc
- [x] makeConstantClassWrapper
  this is new, should it be mentioned somewhere?
- [x] plotResiduals
- [x] getFeatureImportanceLearner, getFeatureImportance + potential changes/improvements in filters
   page: feature selection
- [x] New "dummy" learners (that disregard features completely) can be fitted now for baseline
comparisons, see "featureless" learners below.
   write a separate tutorial page for this?
- [x] DummyFeaturesWrapper

**Comment by florianfendt** [comment]
I already wrote the part for plotResiduals. Will push this week

**Comment by pandeva** [comment]
I will update the Learner page with the get Functions (`getLearnerId`, `getLearnerType`, `getLearnerPredictType`, `getLearnerPackages`, `getLearnerParamSet`, `getLearnerParVals`, `getLearnerShortName`)

**Comment by schiffner** [comment]
I'm closing this.
Everything that wasn't done has its own issue now.
